source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '13.0'
use_frameworks!

target 'JHGPopupKitDemo' do  

pod 'JHGPopupKit', :path => '../'
pod 'JHGPopupManager', :git => 'https://github.com/xq-120/JHGPopupManager.git', :commit => '5a75d0a'
pod 'SnapKit', '~> 5.0.0'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
